# Generated by Django 5.0 on 2023-12-21 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}$')])),
                ('city', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$')])),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adress',
                'verbose_name_plural': 'Adresses',
                'db_table': 'Adress',
                'ordering': ['id'],
            },
        ),
    ]
