# Generated by Django 5.0 on 2023-12-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersManagement', '0004_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addressLine1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='addressLine2',
        ),
    ]
