# Generated by Django 5.0 on 2023-12-26 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_cart_options_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}$')])),
                ('city', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$')])),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$')])),
            ],
            options={
                'verbose_name': 'ShippingAdress',
                'verbose_name_plural': 'ShippingAdresses',
                'db_table': 'ShippingAdress',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Enviado', 'Enviado'), ('Recebido', 'Recebido'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.shippingaddress'),
        ),
    ]
