# Generated by Django 5.0 on 2023-12-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_payment_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addressLine1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='addressLine2',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
