# Generated by Django 5.0 on 2023-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_rename_addressline1_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
