# Generated by Django 5.0 on 2023-12-26 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='expiration_month',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expiration_year',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$')]),
            preserve_default=False,
        ),
    ]
