# Generated by Django 5.0 on 2023-12-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
