# Generated by Django 5.0 on 2023-12-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='nn'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='nn'),
        ),
    ]
