# Generated by Django 5.0 on 2023-12-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_category_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
